apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 6 
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
      - name: azure-vote-front
#        image: ghcr.io/arogic/cicd-playground