name: 'Ansible-Vault'

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check if github cli is installed
      run: |
        pwd
        ls -la
        gh --version
        echo "${{ github.workspace }}"
        ls -ltr ${{ github.workspace }}

    # - uses: ballistax/ansible-vault-action@master
    - name: Decrypt Secrets
      uses: ballistax/ansible-vault-action@v1.0
      with:
        vault_key: ${{ secrets.VAULT_KEY }}
        args: decrypt secret.json

    - name: Show Decrypted Content
      run: |
        sudo chmod 0644 secret.json
        jq .credentials secret.json

    - name: Encrypt Secrets
      uses: ballistax/ansible-vault-action@v1.0
      with:
        vault_key: ${{ secrets.VAULT_KEY }}
        args: encrypt secret.json

    - name: Show Encrypted Content
      run: |
        sudo chmod 0644 secret.json
        cat secret.json
