# Define a name of the workflow
name: Test CalVer

# This controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.calver.outputs.release }}

    steps:
      - uses: actions/checkout@v2

      - name: Calver Release
        uses: StephaneBour/actions-calver@v1.4.3
        # uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y-%m-%d.${{ github.run_number }}"
          # release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        env:
          # VERSION: ${{ steps.calver.outputs.release }}.${{ env.github_run_number }}
          VERSION: "${{ steps.calver.outputs.release }}"
        run: |
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "VERSION:  ${VERSION}"
          
  test2:
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
    - name: Deploy2
      run: |
        echo "VERSION:  ${VERSION}"
