name: Generate Workflow

on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Create Workflow
        run: |
          echo """on:
            workflow_dispatch:
          jobs:
            testwf:
              runs-on: ubuntu-latest
              steps:
                - run: echo \"Hello World\"
          """  > ${{ github.workspace }}/.github/workflows/test-workflow.yml
          cat ${{ github.workspace }}/.github/workflows/test-workflow.yml

      - name: commit
        run: |
          if [ $(git diff-index --name-only --diff-filter=d HEAD | grep 'test-workflow.yml') ]
          then
            git config --global user.email "a.rogi@gmail.com"
            git config --global user.name "arogic"
            git add ${{ github.workspace }}/.github/workflows/*
            git commit -m "Updated Workflow"
            git push
          else
            echo "No changes"
          fi
