name: Reusable workflow example

on:
  workflow_call:
    inputs:
      DRY_RUN:
        required: true
        type: boolean
        default: 'true'

jobs:
  example_job:
    name: Pass input my-action
    runs-on: ubuntu-latest
    steps:
      - name: test boolean
        run: |
          echo ${{ inputs.DRY_RUN }}