# Define a name of the workflow
name: Deploy ArgoCD apps

on:
  # Triggers the workflow on pull request events but only for the main branch
  #  pull_request:
  #    types:
  #      - closed
  #    branches:
  #      - main
  #    paths:
  #      - manifests/argocd/environments/**

  workflow_dispatch:

jobs:
  argocd-deploy-apps-preproduction:
    environment: preproduction
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        run: |
         echo "RESOURCE_GROUP=resource_group" >> $GITHUB_ENV
         echo "CLUSTER_NAME=cluster_name" >> $GITHUB_ENV
         echo "AZURE_CREDENTIALS={\"clientId\": \"${{ env.ARM_CLIENT_ID }}\", \"clientSecret\": \"${{ env.ARM_CLIENT_SECRET }}\", \"subscriptionId\": \"${{ env.ARM_SUBSCRIPTION_ID }}\", \"tenantId\": \"${{ env.ARM_TENANT_ID }}\"}" >> $GITHUB_ENV 

      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.RESOURCE_GROUP }}"
          echo ${{ env.CLUSTER_NAME }}
          echo "${{ env.AZURE_CREDENTIALS }}" # This will output 'yellow'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
