name: 'Test'

on:
  push:
    branches:
      - main

  workflow_dispatch:
# env:
#   ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
#   ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
#   ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
#   BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP }}
#   BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
#   BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
#   BACKEND_TF_STATE_FILE_NAME: test/inf.tfstate
#   TERRAFORM_VERSION: 1.1.2

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check if github cli is installed
      run: |
        pwd
        ls -la
        gh --version
        echo "${{ github.workspace }}"
        ls -ltr ${{ github.workspace }}

#    - uses: ballistax/ansible-vault-action@master
#      with:
#        vault_key: ${{ secrets.VAULT_KEY }}
#        args: decrypt secret.json --output foo.json

    - uses: anthonykgross/ansible-vault-cli-github-action@v1
      with:
        vault_key: ${{ secrets.VAULT_KEY }}
        command: "ansible-vault decrypt secret.json"

    - name: Show Content
      run: |
        ls -ltr
        sudo chmod 0644 secret.json
        jq .credentials secret.json
        # jq .credentials foo.json
        # cat secret.json

    - name: Run script
      env:
        GIT_BRANCH: release/release-${{ github.run_id }}
        GIT_BASE_BRANCH: main
        GITHUB_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: 1.2.${{ github.run_id }}
      run: |
        ${{ github.workspace }}/.github/scripts/get-merge-commit.sh
